import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/app/providers";
import { Noto_Sans } from 'next/font/google'

const NotoSans = Noto_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='light'>
      <body className={`${NotoSans.className} antialiased text-gray-800`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
